import Anthropic from '@anthropic-ai/sdk';
import { pool } from '../dbConfig.js';

/**
 * AI service — Anthropic Claude API.
 *
 * Works in two modes, decided by environment variables (see .env.example),
 * mirroring the WhatsApp integration:
 *
 *  - disabled (default): no ANTHROPIC_API_KEY → every helper returns null and
 *    callers fall back to the existing heuristics/templates. Safe for dev.
 *  - live: ANTHROPIC_API_KEY set (and AI_ENABLED not "false") → suggestions,
 *    candidate screening scores, follow-up scripts and job descriptions are
 *    generated by Claude.
 *
 * Every helper is fail-soft: an API error is logged and null is returned so
 * no user-facing request ever fails because of the AI layer.
 */

function cfg() {
  return {
    apiKey: process.env.ANTHROPIC_API_KEY || '',
    enabled: process.env.AI_ENABLED !== 'false',
    model: process.env.ANTHROPIC_MODEL || 'claude-opus-4-8',
  };
}

export function aiMode(): 'live' | 'disabled' {
  const c = cfg();
  return c.enabled && c.apiKey ? 'live' : 'disabled';
}

/** Map Anthropic API errors to recruiter-friendly messages. */
export function humanizeAnthropicError(err: unknown): string | null {
  const msg = err instanceof Error ? err.message : String(err);
  if (/credit balance is too low/i.test(msg)) {
    return 'Anthropic API credits exhausted. Add credits at platform.claude.com → Plans & Billing, then retry.';
  }
  if (/invalid x-api-key|authentication/i.test(msg)) {
    return 'Invalid Anthropic API key. Check ANTHROPIC_API_KEY in .env and restart the server.';
  }
  if (/rate limit/i.test(msg)) {
    return 'Anthropic API rate limit reached. Wait a moment and retry.';
  }
  return null;
}

let client: Anthropic | null = null;
function getClient(): Anthropic {
  if (!client) {
    // Suggestion endpoints are user-facing: keep latency bounded rather than
    // retrying into a slow success.
    client = new Anthropic({ timeout: 30_000, maxRetries: 1 });
  }
  return client;
}

/** Run a prompt that must return JSON matching `schema`; null on any failure. */
async function jsonCall<T>(
  system: string,
  prompt: string,
  schema: Record<string, unknown>,
  effort: 'low' | 'medium' | 'high' = 'low'
): Promise<T | null> {
  const result = await jsonCallResult<T>(system, prompt, schema, effort);
  return result.data;
}

/** Like jsonCall but surfaces API errors (billing, auth) for user-facing endpoints. */
async function jsonCallResult<T>(
  system: string,
  prompt: string,
  schema: Record<string, unknown>,
  effort: 'low' | 'medium' | 'high' = 'low'
): Promise<{ data: T | null; error?: string }> {
  if (aiMode() === 'disabled') {
    return { data: null, error: 'AI not configured — set ANTHROPIC_API_KEY on the server' };
  }
  try {
    const response = await getClient().messages.create({
      model: cfg().model,
      max_tokens: 2048,
      thinking: { type: 'adaptive' },
      output_config: {
        effort,
        format: { type: 'json_schema', schema },
      },
      system,
      messages: [{ role: 'user', content: prompt }],
    });
    if (response.stop_reason === 'refusal') return { data: null };
    const text = response.content.find((b) => b.type === 'text')?.text;
    return { data: text ? (JSON.parse(text) as T) : null };
  } catch (err) {
    console.warn('AI call failed:', (err as Error).message);
    return { data: null, error: humanizeAnthropicError(err) ?? undefined };
  }
}

/** Run a prompt that returns plain text; null on any failure. */
async function textCall(
  system: string,
  prompt: string,
  effort: 'low' | 'medium' | 'high' = 'low'
): Promise<string | null> {
  if (aiMode() === 'disabled') return null;
  try {
    const response = await getClient().messages.create({
      model: cfg().model,
      max_tokens: 2048,
      thinking: { type: 'adaptive' },
      output_config: { effort },
      system,
      messages: [{ role: 'user', content: prompt }],
    });
    if (response.stop_reason === 'refusal') return null;
    const text = response.content.find((b) => b.type === 'text')?.text?.trim();
    return text || null;
  } catch (err) {
    console.warn('AI call failed:', (err as Error).message);
    return null;
  }
}

// ── Message suggestions (WhatsApp inbox + candidate outreach) ──────────

export interface SuggestionContext {
  candidateName: string;
  stage: string;
  jobTitle?: string | null;
  jobLocation?: string | null;
  salaryExpectation?: string | null;
  upcomingInterviewAt?: string | null;
  recentMessages?: { direction: 'candidate' | 'recruiter'; content: string }[];
  purpose: 'whatsapp_reply' | 'outreach';
}

const SUGGESTIONS_SCHEMA = {
  type: 'object',
  properties: {
    suggestions: {
      type: 'array',
      items: { type: 'string' },
      description: 'Exactly 3 short candidate-facing messages',
    },
  },
  required: ['suggestions'],
  additionalProperties: false,
} as const;

export async function suggestMessages(ctx: SuggestionContext): Promise<string[] | null> {
  const conversation = (ctx.recentMessages || [])
    .map((m) => `${m.direction === 'candidate' ? 'Candidate' : 'Recruiter'}: ${m.content}`)
    .join('\n');

  const system =
    'You draft WhatsApp messages a recruiter sends to a job candidate. ' +
    'Messages must be warm, professional, specific to the context, and under 200 characters each. ' +
    'No emoji spam, no placeholders like [date] — if a detail is unknown, phrase the message so it is not needed. ' +
    'Return exactly 3 distinct options.';

  const prompt = [
    `Candidate: ${ctx.candidateName} (pipeline stage: ${ctx.stage})`,
    ctx.jobTitle ? `Role: ${ctx.jobTitle}${ctx.jobLocation ? `, ${ctx.jobLocation}` : ''}` : null,
    ctx.salaryExpectation ? `Salary expectation on file: ${ctx.salaryExpectation}` : null,
    ctx.upcomingInterviewAt
      ? `Upcoming interview: ${new Date(ctx.upcomingInterviewAt).toLocaleString()}`
      : null,
    conversation ? `Recent conversation (newest last):\n${conversation}` : null,
    ctx.purpose === 'whatsapp_reply'
      ? 'Task: suggest 3 replies the recruiter could send next in this conversation.'
      : 'Task: suggest 3 outreach messages to move this candidate forward in the pipeline.',
  ]
    .filter(Boolean)
    .join('\n');

  const result = await jsonCall<{ suggestions: string[] }>(system, prompt, SUGGESTIONS_SCHEMA);
  const suggestions = result?.suggestions?.filter((s) => typeof s === 'string' && s.trim());
  return suggestions?.length ? suggestions.slice(0, 3) : null;
}

// ── Candidate screening score ──────────────────────────────────────────

export interface CandidateScoreInput {
  name: string;
  skills: string[];
  experienceYears: number;
  notes?: string | null;
  salaryExpectation?: string | null;
  jobTitle?: string | null;
  jobDescription?: string | null;
  jobLocation?: string | null;
}

export interface CandidateScore {
  score: number; // 0–10, one decimal
  strengths: string[];
  gaps: string[];
  summary: string;
}

const SCORE_SCHEMA = {
  type: 'object',
  properties: {
    score: { type: 'number', description: 'Fit score from 0 to 10, one decimal place' },
    strengths: { type: 'array', items: { type: 'string' } },
    gaps: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string', description: 'One-sentence screening summary, max 150 chars' },
  },
  required: ['score', 'strengths', 'gaps', 'summary'],
  additionalProperties: false,
} as const;

export async function scoreCandidate(input: CandidateScoreInput): Promise<CandidateScore | null> {
  const system =
    'You are a recruitment screening assistant. Score how well a candidate profile fits a role ' +
    'on a 0–10 scale (10 = ideal fit). Base the score only on the provided profile vs the role. ' +
    'If no role details are given, score general employability for the skills listed. Be calibrated: ' +
    'most candidates land between 4 and 8; reserve 9+ for exceptional matches.';

  const prompt = [
    `Candidate: ${input.name}`,
    `Skills: ${input.skills.length ? input.skills.join(', ') : '(none listed)'}`,
    `Experience: ${input.experienceYears} years`,
    input.salaryExpectation ? `Salary expectation: ${input.salaryExpectation}` : null,
    input.notes ? `Recruiter notes: ${input.notes}` : null,
    input.jobTitle
      ? `Role: ${input.jobTitle}${input.jobLocation ? `, ${input.jobLocation}` : ''}`
      : 'Role: not assigned yet',
    input.jobDescription ? `Job description:\n${input.jobDescription}` : null,
  ]
    .filter(Boolean)
    .join('\n');

  const result = await jsonCall<CandidateScore>(system, prompt, SCORE_SCHEMA, 'medium');
  if (!result || typeof result.score !== 'number') return null;
  result.score = Math.round(Math.min(10, Math.max(0, result.score)) * 10) / 10;
  return result;
}

/**
 * Background re-score: fetch the candidate + job, ask Claude for a fit score,
 * update ai_score and record the assessment on the candidate's timeline.
 * Fire-and-forget — call sites must not await this on the request path.
 */
export async function rescoreCandidate(tenantId: number, candidateId: number): Promise<void> {
  if (aiMode() === 'disabled') return;
  try {
    const { rows } = await pool.query(
      `SELECT c.name, c.skills, c.experience_years, c.notes, c.salary_expectation,
              j.title AS job_title, j.description AS job_description, j.location AS job_location
       FROM candidates c
       LEFT JOIN jobs j ON j.id = c.job_id AND j.tenant_id = c.tenant_id
       WHERE c.id = $1 AND c.tenant_id = $2`,
      [candidateId, tenantId]
    );
    const c = rows[0];
    if (!c) return;

    const result = await scoreCandidate({
      name: c.name,
      skills: Array.isArray(c.skills) ? c.skills : [],
      experienceYears: Number(c.experience_years) || 0,
      notes: c.notes,
      salaryExpectation: c.salary_expectation,
      jobTitle: c.job_title,
      jobDescription: c.job_description,
      jobLocation: c.job_location,
    });
    if (!result) return;

    await pool.query(
      'UPDATE candidates SET ai_score = $1, updated_at = NOW() WHERE id = $2 AND tenant_id = $3',
      [result.score, candidateId, tenantId]
    );
    const detail = [
      result.summary,
      result.strengths.length ? `Strengths: ${result.strengths.slice(0, 3).join('; ')}` : null,
      result.gaps.length ? `Gaps: ${result.gaps.slice(0, 3).join('; ')}` : null,
    ]
      .filter(Boolean)
      .join(' · ');
    await pool.query(
      'INSERT INTO activities (type, description, candidate_id, tenant_id) VALUES ($1, $2, $3, $4)',
      ['screening', `AI screening: ${result.score}/10 — ${detail}`.slice(0, 500), candidateId, tenantId]
    );
  } catch (err) {
    console.warn(`AI rescore failed for candidate ${candidateId}:`, (err as Error).message);
  }
}

// ── Follow-up call script ──────────────────────────────────────────────

export interface FollowUpScriptInput {
  category: string;
  type: string;
  dueAt: string;
  milestoneDay?: number | null;
  candidateName: string;
  stage: string;
  jobTitle?: string | null;
  interviewAt?: string | null;
  expectedJoiningAt?: string | null;
  joinedAt?: string | null;
  priorOutcomes?: { category: string; outcome: string; completedAt: string }[];
}

export async function generateFollowUpScript(input: FollowUpScriptInput): Promise<string | null> {
  const system =
    'You write short call scripts for recruiters following up with job candidates. ' +
    'Output only the script: 2–4 sentences of what the recruiter should say/cover, ' +
    'personalized to the candidate situation. Plain text, no headings, max 350 characters.';

  const outcomes = (input.priorOutcomes || [])
    .map((o) => `${o.category}: ${o.outcome} (${new Date(o.completedAt).toLocaleDateString()})`)
    .join('; ');

  const prompt = [
    `Follow-up type: ${input.category} via ${input.type}, due ${new Date(input.dueAt).toLocaleString()}`,
    input.milestoneDay != null ? `Milestone day: ${input.milestoneDay}` : null,
    `Candidate: ${input.candidateName} (stage: ${input.stage})`,
    input.jobTitle ? `Role: ${input.jobTitle}` : null,
    input.interviewAt ? `Interview at: ${new Date(input.interviewAt).toLocaleString()}` : null,
    input.expectedJoiningAt
      ? `Expected joining: ${new Date(input.expectedJoiningAt).toLocaleDateString()}`
      : null,
    input.joinedAt ? `Joined on: ${new Date(input.joinedAt).toLocaleDateString()}` : null,
    outcomes ? `Previous follow-up outcomes: ${outcomes}` : null,
    'Write the call script for this follow-up.',
  ]
    .filter(Boolean)
    .join('\n');

  return textCall(system, prompt);
}

// ── Job description generation ─────────────────────────────────────────

export interface JobDescriptionInput {
  title: string;
  client?: string | null;
  location?: string | null;
  openPositions?: number | null;
  notes?: string | null;
}

export async function generateJobDescription(input: JobDescriptionInput): Promise<string | null> {
  const system =
    'You write job descriptions for a recruitment agency. Output plain text (no markdown headers) ' +
    'with short sections: role summary, key responsibilities (3-5 bullets using "- "), ' +
    'requirements (3-5 bullets), and what is offered. Keep it under 250 words. ' +
    'Do not invent salary figures or company facts not provided.';

  const prompt = [
    `Job title: ${input.title}`,
    input.client ? `Hiring company: ${input.client}` : null,
    input.location ? `Location: ${input.location}` : null,
    input.openPositions ? `Open positions: ${input.openPositions}` : null,
    input.notes ? `Extra notes from the recruiter: ${input.notes}` : null,
    'Write the job description.',
  ]
    .filter(Boolean)
    .join('\n');

  return textCall(system, prompt, 'medium');
}

// ── Resume parsing ─────────────────────────────────────────────────────

export interface ParsedExperience {
  title: string;
  company: string;
  start_date?: string | null;
  end_date?: string | null;
  description?: string | null;
}

export interface ParsedEducation {
  degree: string;
  institution: string;
  year?: string | null;
}

export interface ParsedProject {
  name: string;
  description?: string | null;
  technologies?: string[];
}

export interface ParsedCertification {
  name: string;
  issuer?: string | null;
  date?: string | null;
}

export interface ParsedProfile {
  name: string;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  github?: string | null;
  portfolio?: string | null;
  current_company?: string | null;
  previous_companies?: string[];
  experience?: ParsedExperience[];
  education?: ParsedEducation[];
  projects?: ParsedProject[];
  skills?: string[];
  technical_skills?: string[];
  soft_skills?: string[];
  certifications?: ParsedCertification[];
  current_salary?: string | null;
  expected_salary?: string | null;
  notice_period?: string | null;
  current_location?: string | null;
  preferred_location?: string | null;
  languages?: string[];
  professional_summary?: string | null;
  total_experience_years?: number | null;
  confidence: number;
}

const PARSED_EXPERIENCE_SCHEMA = {
  type: 'object',
  properties: {
    title: { type: 'string' },
    company: { type: 'string' },
    start_date: { type: ['string', 'null'] },
    end_date: { type: ['string', 'null'] },
    description: { type: ['string', 'null'] },
  },
  required: ['title', 'company'],
  additionalProperties: false,
} as const;

const PARSED_EDUCATION_SCHEMA = {
  type: 'object',
  properties: {
    degree: { type: 'string' },
    institution: { type: 'string' },
    year: { type: ['string', 'null'] },
  },
  required: ['degree', 'institution'],
  additionalProperties: false,
} as const;

const PARSED_PROJECT_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    description: { type: ['string', 'null'] },
    technologies: { type: 'array', items: { type: 'string' } },
  },
  required: ['name'],
  additionalProperties: false,
} as const;

const PARSED_CERTIFICATION_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    issuer: { type: ['string', 'null'] },
    date: { type: ['string', 'null'] },
  },
  required: ['name'],
  additionalProperties: false,
} as const;

const PARSE_RESUME_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    email: { type: ['string', 'null'] },
    phone: { type: ['string', 'null'] },
    linkedin: { type: ['string', 'null'] },
    github: { type: ['string', 'null'] },
    portfolio: { type: ['string', 'null'] },
    current_company: { type: ['string', 'null'] },
    previous_companies: { type: 'array', items: { type: 'string' } },
    experience: { type: 'array', items: PARSED_EXPERIENCE_SCHEMA },
    education: { type: 'array', items: PARSED_EDUCATION_SCHEMA },
    projects: { type: 'array', items: PARSED_PROJECT_SCHEMA },
    skills: { type: 'array', items: { type: 'string' } },
    technical_skills: { type: 'array', items: { type: 'string' } },
    soft_skills: { type: 'array', items: { type: 'string' } },
    certifications: { type: 'array', items: PARSED_CERTIFICATION_SCHEMA },
    current_salary: { type: ['string', 'null'] },
    expected_salary: { type: ['string', 'null'] },
    notice_period: { type: ['string', 'null'] },
    current_location: { type: ['string', 'null'] },
    preferred_location: { type: ['string', 'null'] },
    languages: { type: 'array', items: { type: 'string' } },
    professional_summary: { type: ['string', 'null'] },
    total_experience_years: { type: ['number', 'null'] },
    confidence: {
      type: 'number',
      description: 'Self-assessed extraction confidence from 0.0 to 1.0',
    },
  },
  required: ['name', 'confidence'],
  additionalProperties: false,
} as const;

/** Derive a confidence score from field completeness when AI self-score is missing. */
export function computeParseConfidence(profile: ParsedProfile): number {
  const checks = [
    profile.name,
    profile.email,
    profile.phone,
    profile.skills?.length,
    profile.experience?.length,
    profile.education?.length,
    profile.professional_summary,
  ];
  const filled = checks.filter((v) => (Array.isArray(v) ? v.length > 0 : Boolean(v))).length;
  const heuristic = Math.min(1, filled / checks.length);
  const raw = typeof profile.confidence === 'number' && !Number.isNaN(profile.confidence)
    ? profile.confidence
    : heuristic;
  return Math.round(Math.min(1, Math.max(0, raw)) * 100) / 100;
}

export async function parseResume(
  text: string,
  filename: string
): Promise<{ profile: ParsedProfile | null; error?: string }> {
  if (!text.trim()) {
    return { profile: null, error: 'Resume text is empty after extraction.' };
  }

  const system =
    'You extract structured candidate profile data from resume text for a recruitment ATS. ' +
    'Only include information explicitly present or clearly inferable from the resume. ' +
    'Use null for missing scalar fields and empty arrays for missing lists. ' +
    'Normalize phone numbers with country code when possible. ' +
    'Split skills into general skills, technical_skills, and soft_skills when distinguishable. ' +
    'Set confidence (0.0–1.0) based on how complete and unambiguous the extraction is.';

  const prompt = [
    `Resume filename: ${filename}`,
    'Resume text:',
    text.slice(0, 120_000),
    'Extract all available profile fields.',
  ].join('\n\n');

  const { data: result, error } = await jsonCallResult<ParsedProfile>(
    system,
    prompt,
    PARSE_RESUME_SCHEMA,
    'high'
  );
  if (error) return { profile: null, error };
  if (!result?.name?.trim()) {
    return { profile: null, error: 'AI could not extract a candidate name from this resume.' };
  }

  result.confidence = computeParseConfidence(result);
  if (result.total_experience_years != null) {
    result.total_experience_years =
      Math.round(Math.max(0, Number(result.total_experience_years)) * 10) / 10;
  }

  return { profile: result };
}
