import Anthropic from '@anthropic-ai/sdk';
import { pool } from '../dbConfig.js';

/**
 * AI service — Anthropic Claude API.
 *
 * Works in two modes, decided by environment variables (see .env.example),
 * mirroring the WhatsApp integration:
 *
 *  - disabled (default): no ANTHROPIC_API_KEY → every helper returns null and
 *    callers fall back to the existing heuristics/templates. Safe for dev.
 *  - live: ANTHROPIC_API_KEY set (and AI_ENABLED not "false") → suggestions,
 *    candidate screening scores, follow-up scripts and job descriptions are
 *    generated by Claude.
 *
 * Every helper is fail-soft: an API error is logged and null is returned so
 * no user-facing request ever fails because of the AI layer.
 */

function cfg() {
  return {
    apiKey: process.env.ANTHROPIC_API_KEY || '',
    enabled: process.env.AI_ENABLED !== 'false',
    model: process.env.ANTHROPIC_MODEL || 'claude-opus-4-8',
  };
}

export function aiMode(): 'live' | 'disabled' {
  const c = cfg();
  return c.enabled && c.apiKey ? 'live' : 'disabled';
}

let client: Anthropic | null = null;
function getClient(): Anthropic {
  if (!client) {
    // Suggestion endpoints are user-facing: keep latency bounded rather than
    // retrying into a slow success.
    client = new Anthropic({ timeout: 30_000, maxRetries: 1 });
  }
  return client;
}

/** Run a prompt that must return JSON matching `schema`; null on any failure. */
async function jsonCall<T>(
  system: string,
  prompt: string,
  schema: Record<string, unknown>,
  effort: 'low' | 'medium' | 'high' = 'low'
): Promise<T | null> {
  if (aiMode() === 'disabled') return null;
  try {
    const response = await getClient().messages.create({
      model: cfg().model,
      max_tokens: 2048,
      thinking: { type: 'adaptive' },
      output_config: {
        effort,
        format: { type: 'json_schema', schema },
      },
      system,
      messages: [{ role: 'user', content: prompt }],
    });
    if (response.stop_reason === 'refusal') return null;
    const text = response.content.find((b) => b.type === 'text')?.text;
    return text ? (JSON.parse(text) as T) : null;
  } catch (err) {
    console.warn('AI call failed:', (err as Error).message);
    return null;
  }
}

/** Run a prompt that returns plain text; null on any failure. */
async function textCall(
  system: string,
  prompt: string,
  effort: 'low' | 'medium' | 'high' = 'low'
): Promise<string | null> {
  if (aiMode() === 'disabled') return null;
  try {
    const response = await getClient().messages.create({
      model: cfg().model,
      max_tokens: 2048,
      thinking: { type: 'adaptive' },
      output_config: { effort },
      system,
      messages: [{ role: 'user', content: prompt }],
    });
    if (response.stop_reason === 'refusal') return null;
    const text = response.content.find((b) => b.type === 'text')?.text?.trim();
    return text || null;
  } catch (err) {
    console.warn('AI call failed:', (err as Error).message);
    return null;
  }
}

// ── Message suggestions (WhatsApp inbox + candidate outreach) ──────────

export interface SuggestionContext {
  candidateName: string;
  stage: string;
  jobTitle?: string | null;
  jobLocation?: string | null;
  salaryExpectation?: string | null;
  upcomingInterviewAt?: string | null;
  recentMessages?: { direction: 'candidate' | 'recruiter'; content: string }[];
  purpose: 'whatsapp_reply' | 'outreach';
}

const SUGGESTIONS_SCHEMA = {
  type: 'object',
  properties: {
    suggestions: {
      type: 'array',
      items: { type: 'string' },
      description: 'Exactly 3 short candidate-facing messages',
    },
  },
  required: ['suggestions'],
  additionalProperties: false,
} as const;

export async function suggestMessages(ctx: SuggestionContext): Promise<string[] | null> {
  const conversation = (ctx.recentMessages || [])
    .map((m) => `${m.direction === 'candidate' ? 'Candidate' : 'Recruiter'}: ${m.content}`)
    .join('\n');

  const system =
    'You draft WhatsApp messages a recruiter sends to a job candidate. ' +
    'Messages must be warm, professional, specific to the context, and under 200 characters each. ' +
    'No emoji spam, no placeholders like [date] — if a detail is unknown, phrase the message so it is not needed. ' +
    'Return exactly 3 distinct options.';

  const prompt = [
    `Candidate: ${ctx.candidateName} (pipeline stage: ${ctx.stage})`,
    ctx.jobTitle ? `Role: ${ctx.jobTitle}${ctx.jobLocation ? `, ${ctx.jobLocation}` : ''}` : null,
    ctx.salaryExpectation ? `Salary expectation on file: ${ctx.salaryExpectation}` : null,
    ctx.upcomingInterviewAt
      ? `Upcoming interview: ${new Date(ctx.upcomingInterviewAt).toLocaleString()}`
      : null,
    conversation ? `Recent conversation (newest last):\n${conversation}` : null,
    ctx.purpose === 'whatsapp_reply'
      ? 'Task: suggest 3 replies the recruiter could send next in this conversation.'
      : 'Task: suggest 3 outreach messages to move this candidate forward in the pipeline.',
  ]
    .filter(Boolean)
    .join('\n');

  const result = await jsonCall<{ suggestions: string[] }>(system, prompt, SUGGESTIONS_SCHEMA);
  const suggestions = result?.suggestions?.filter((s) => typeof s === 'string' && s.trim());
  return suggestions?.length ? suggestions.slice(0, 3) : null;
}

// ── Candidate screening score ──────────────────────────────────────────

export interface CandidateScoreInput {
  name: string;
  skills: string[];
  experienceYears: number;
  notes?: string | null;
  salaryExpectation?: string | null;
  jobTitle?: string | null;
  jobDescription?: string | null;
  jobLocation?: string | null;
}

export interface CandidateScore {
  score: number; // 0–10, one decimal
  strengths: string[];
  gaps: string[];
  summary: string;
}

const SCORE_SCHEMA = {
  type: 'object',
  properties: {
    score: { type: 'number', description: 'Fit score from 0 to 10, one decimal place' },
    strengths: { type: 'array', items: { type: 'string' } },
    gaps: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string', description: 'One-sentence screening summary, max 150 chars' },
  },
  required: ['score', 'strengths', 'gaps', 'summary'],
  additionalProperties: false,
} as const;

export async function scoreCandidate(input: CandidateScoreInput): Promise<CandidateScore | null> {
  const system =
    'You are a recruitment screening assistant. Score how well a candidate profile fits a role ' +
    'on a 0–10 scale (10 = ideal fit). Base the score only on the provided profile vs the role. ' +
    'If no role details are given, score general employability for the skills listed. Be calibrated: ' +
    'most candidates land between 4 and 8; reserve 9+ for exceptional matches.';

  const prompt = [
    `Candidate: ${input.name}`,
    `Skills: ${input.skills.length ? input.skills.join(', ') : '(none listed)'}`,
    `Experience: ${input.experienceYears} years`,
    input.salaryExpectation ? `Salary expectation: ${input.salaryExpectation}` : null,
    input.notes ? `Recruiter notes: ${input.notes}` : null,
    input.jobTitle
      ? `Role: ${input.jobTitle}${input.jobLocation ? `, ${input.jobLocation}` : ''}`
      : 'Role: not assigned yet',
    input.jobDescription ? `Job description:\n${input.jobDescription}` : null,
  ]
    .filter(Boolean)
    .join('\n');

  const result = await jsonCall<CandidateScore>(system, prompt, SCORE_SCHEMA, 'medium');
  if (!result || typeof result.score !== 'number') return null;
  result.score = Math.round(Math.min(10, Math.max(0, result.score)) * 10) / 10;
  return result;
}

/**
 * Background re-score: fetch the candidate + job, ask Claude for a fit score,
 * update ai_score and record the assessment on the candidate's timeline.
 * Fire-and-forget — call sites must not await this on the request path.
 */
export async function rescoreCandidate(tenantId: number, candidateId: number): Promise<void> {
  if (aiMode() === 'disabled') return;
  try {
    const { rows } = await pool.query(
      `SELECT c.name, c.skills, c.experience_years, c.notes, c.salary_expectation,
              j.title AS job_title, j.description AS job_description, j.location AS job_location
       FROM candidates c
       LEFT JOIN jobs j ON j.id = c.job_id AND j.tenant_id = c.tenant_id
       WHERE c.id = $1 AND c.tenant_id = $2`,
      [candidateId, tenantId]
    );
    const c = rows[0];
    if (!c) return;

    const result = await scoreCandidate({
      name: c.name,
      skills: Array.isArray(c.skills) ? c.skills : [],
      experienceYears: Number(c.experience_years) || 0,
      notes: c.notes,
      salaryExpectation: c.salary_expectation,
      jobTitle: c.job_title,
      jobDescription: c.job_description,
      jobLocation: c.job_location,
    });
    if (!result) return;

    await pool.query(
      'UPDATE candidates SET ai_score = $1, updated_at = NOW() WHERE id = $2 AND tenant_id = $3',
      [result.score, candidateId, tenantId]
    );
    const detail = [
      result.summary,
      result.strengths.length ? `Strengths: ${result.strengths.slice(0, 3).join('; ')}` : null,
      result.gaps.length ? `Gaps: ${result.gaps.slice(0, 3).join('; ')}` : null,
    ]
      .filter(Boolean)
      .join(' · ');
    await pool.query(
      'INSERT INTO activities (type, description, candidate_id, tenant_id) VALUES ($1, $2, $3, $4)',
      ['screening', `AI screening: ${result.score}/10 — ${detail}`.slice(0, 500), candidateId, tenantId]
    );
  } catch (err) {
    console.warn(`AI rescore failed for candidate ${candidateId}:`, (err as Error).message);
  }
}

// ── Follow-up call script ──────────────────────────────────────────────

export interface FollowUpScriptInput {
  category: string;
  type: string;
  dueAt: string;
  milestoneDay?: number | null;
  candidateName: string;
  stage: string;
  jobTitle?: string | null;
  interviewAt?: string | null;
  expectedJoiningAt?: string | null;
  joinedAt?: string | null;
  priorOutcomes?: { category: string; outcome: string; completedAt: string }[];
}

export async function generateFollowUpScript(input: FollowUpScriptInput): Promise<string | null> {
  const system =
    'You write short call scripts for recruiters following up with job candidates. ' +
    'Output only the script: 2–4 sentences of what the recruiter should say/cover, ' +
    'personalized to the candidate situation. Plain text, no headings, max 350 characters.';

  const outcomes = (input.priorOutcomes || [])
    .map((o) => `${o.category}: ${o.outcome} (${new Date(o.completedAt).toLocaleDateString()})`)
    .join('; ');

  const prompt = [
    `Follow-up type: ${input.category} via ${input.type}, due ${new Date(input.dueAt).toLocaleString()}`,
    input.milestoneDay != null ? `Milestone day: ${input.milestoneDay}` : null,
    `Candidate: ${input.candidateName} (stage: ${input.stage})`,
    input.jobTitle ? `Role: ${input.jobTitle}` : null,
    input.interviewAt ? `Interview at: ${new Date(input.interviewAt).toLocaleString()}` : null,
    input.expectedJoiningAt
      ? `Expected joining: ${new Date(input.expectedJoiningAt).toLocaleDateString()}`
      : null,
    input.joinedAt ? `Joined on: ${new Date(input.joinedAt).toLocaleDateString()}` : null,
    outcomes ? `Previous follow-up outcomes: ${outcomes}` : null,
    'Write the call script for this follow-up.',
  ]
    .filter(Boolean)
    .join('\n');

  return textCall(system, prompt);
}

// ── Job description generation ─────────────────────────────────────────

export interface JobDescriptionInput {
  title: string;
  client?: string | null;
  location?: string | null;
  openPositions?: number | null;
  notes?: string | null;
}

export async function generateJobDescription(input: JobDescriptionInput): Promise<string | null> {
  const system =
    'You write job descriptions for a recruitment agency. Output plain text (no markdown headers) ' +
    'with short sections: role summary, key responsibilities (3-5 bullets using "- "), ' +
    'requirements (3-5 bullets), and what is offered. Keep it under 250 words. ' +
    'Do not invent salary figures or company facts not provided.';

  const prompt = [
    `Job title: ${input.title}`,
    input.client ? `Hiring company: ${input.client}` : null,
    input.location ? `Location: ${input.location}` : null,
    input.openPositions ? `Open positions: ${input.openPositions}` : null,
    input.notes ? `Extra notes from the recruiter: ${input.notes}` : null,
    'Write the job description.',
  ]
    .filter(Boolean)
    .join('\n');

  return textCall(system, prompt, 'medium');
}
